# Generated by Django 5.2.1 on 2025-05-31 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_paths', '0002_alter_learningpath_user_alter_learningpath_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpath',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_paths', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='users',
            field=models.ManyToManyField(related_name='enrolled_paths', to=settings.AUTH_USER_MODEL),
        ),
    ]
