# Generated by Django 5.2.1 on 2025-06-01 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
        ('learning_paths', '0004_alter_pathstep_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathstep',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='pathstep',
            name='skill',
        ),
        migrations.AddField(
            model_name='pathstep',
            name='resources',
            field=models.ManyToManyField(blank=True, related_name='path_steps_featuring_resource', to='careers.learningresource'),
        ),
        migrations.AddField(
            model_name='pathstep',
            name='skill_to_learn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='path_steps_for_skill', to='careers.skill'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths_for_career', to='careers.career'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='duration_weeks',
            field=models.PositiveIntegerField(default=0, help_text='Estimated completion time in weeks'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether path is visible to other users'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='learning_paths_targeting_skill', to='careers.skill'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='enrolled_paths', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pathstep',
            name='estimated_hours',
            field=models.PositiveIntegerField(default=0, help_text='Estimated hours to complete this step'),
        ),
        migrations.AlterField(
            model_name='pathstep',
            name='order',
            field=models.PositiveIntegerField(help_text='Order of the step in the path'),
        ),
        migrations.AlterField(
            model_name='pathstep',
            name='step_type',
            field=models.CharField(choices=[('skill', 'Learn Skill'), ('resource', 'Complete Resource'), ('project', 'Complete Project'), ('assessment', 'Pass Assessment')], default='resource', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpathprogress',
            name='path_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress_entries', to='learning_paths.pathstep'),
        ),
        migrations.AlterField(
            model_name='userpathprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_progress', to=settings.AUTH_USER_MODEL),
        ),
    ]
